name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Simulate Deployment
        run: echo "Website deployed successfully!"
